Coffee-Store/Controllers/CheckTableReservationsController.cs
using Coffee_Store.Data;
using Coffee_Store.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Coffee_Store.Controllers
{
    public class CheckTableReservationsController : Controller
    {
        private readonly ApplicationDBContext _dbContext;

        public CheckTableReservationsController(ApplicationDBContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult CheckTableReservations()
        {
            List<Reservations> obj = _dbContext.Reservations.ToList();
            return View(obj);
        }
    }
}

Coffee-Store/Views/Admin/AddNewMenuItem.cshtml
@model Menu

<section class="add-menu-item" id="add-menu-item">
    <h1 class="heading"><span>Add New Menu Item</span></h1>

    <form method="post" class="add-new-form">
        <div class="form-field">
            <label for="itemName">Item Name</label>
            <input asp-for="ItemName" type="text" id="itemName" required/>
        </div>

        <div class="form-field">
            <label for="description">Description</label>
            <input asp-for="Description" type="text" id="description" required/>
        </div>

        <div class="form-field">
            <label for="price">Price</label>
            <input asp-for="Price" type="number" id="price" required/>
        </div>

        <div class="form-field">
            <label for="url">Image URL</label>
            <input asp-for="Url" type="text" id="url" required/>
        </div>

        <div class="form-actions">
            <button type="submit" class="add-new-menu-item-btn">Submit</button>
            <a href="/Admin/Admin" class="go-back-button">Back</a>
        </div>
    </form>
</section>

Coffee-Store/Views/Admin/Admin.cshtml
@model List<Menu>

<section class="admin" id="admin">
    <h1 class="heading">Admin</h1>
    <h1 class="heading"><span>Manage Menu Items</span></h1>
    
    <div class="add-new">
        <a asp-controller="CheckTableReservations" asp-action="CheckTableReservations" class="add-button">Check Table Reservations</a>
        <a asp-controller="Admin" asp-action="AddNewMenuItem" class="add-button">Add New Menu Item</a>
    </div>

    <table class="admin-table">
        <thead>
            <tr>
                <th>Item Name</th>
                <th>Description</th>
                <th>Price</th> 
                 <th>Edit</th>
                <th>Delete</th> 
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model.OrderBy(u => u.ItemID))
            {
                <tr class="admin-item">
                    <td>@obj.ItemName</td>
                    <td>@obj.Description</td>
                    <td>₹@obj.Price</td>


                    <td><a asp-controller="Admin" asp-action="EditMenuItem" asp-route-id="@obj.ItemID" class="edit-button">Edit</a></td>
                    <td><a asp-controller="Admin" asp-action="DeleteMenuItem" asp-route-id="@obj.ItemID" class="delete-button">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
</section>

Coffee-Store/Views/Admin/DeleteMenuItem.cshtml
@model Menu

<section class="delete-menu-item" id="delete-menu-item">
    <h1 class="heading"><span>Delete Menu Item</span></h1>

    <form method="post" class="delete-menu-item-form">

        <input asp-for="ItemID" type="hidden" />

        <div class="form-field"> 
            <label for="itemName">Item Name</label>
            <input asp-for="ItemName" type="text" id="itemName" disabled />
        </div> 

        <div class="form-field">
            <label for="description">Description</label> 
            <input asp-for="Description" id="description" disabled />
        </div>

        <div class="form-field">
            <label for="price">Price</label>
            <input asp-for="Price" type="number" id="price" disabled />
        </div>

        <div class="form-field">
            <label for="url">Image URL</label> 
            <input asp-for="Url" type="text" id="url" disabled />
        </div>

        <div class="form-actions">
            <button type="submit" class="delete-menu-item-btn">Delete</button>
            <a href="/Admin/Admin" class="go-back-button">Back</a>
        </div>
    </form>
</section>

Coffee-Store/Views/Admin/EditMenuItem.cshtml
@model Menu

<section class="edit-menu-item" id="edit-menu-item">
    <h1 class="heading"><span>Edit Menu Item</span></h1>

    <form method="post" class="edit-menu-item-form">

        <input asp-for="ItemID" type="hidden" />

        <div class="form-field">
            <label for="itemName">Item Name</label>
            <input asp-for="ItemName" type="text" id="itemName" required/>
        </div>

        <div class="form-field">
            <label for="description">Description</label>
            <input asp-for="Description" type="text" id="description" required/>
        </div>

        <div class="form-field">
            <label for="price">Price</label>
            <input asp-for="Price" type="number" id="price" required/>
        </div>

        <div class="form-field">
            <label for="url">Image URL</label>
            <input asp-for="Url" type="text" id="url" required/>
        </div>

        <div class="form-actions">
            <button  type="submit" class="edit-menu-item-btn">Submit</button>
            <a asp-controller="Admin" asp-action="Admin" class="go-back-button">Back</a>
        </div>
    </form>
</section>